# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Pull & Deploy
on:
  push:
    branches: [ $default-branch]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Set up python
      uses: actions/setup-python@v3
      with:
        python-version: "3.9"
    - name: Install dependincies
      run: |
          cd /home/django/retsinformation/retsinfo_app
          sudo -u django rm retsinfo_app/settings/.env
          sudo -u django git pull
          sudo -u django .env/bin/python -c 'from django.core.management.utils import get_random_secret_key; print("SECRET_KEY=" + get_random_secret_key())' >> retsinfo_app/settings/.env
          sudo -u django .env/bin/pip install -r requirements.txt
          #sudo -u django .env/bin/python manage.py collectstatic --noinput
          #sudo -u django .env/bin/python manage.py makemigrations
          #sudo -u django .env/bin/python manage.py migrate
          #systemctl restart gunicorn
